"""empty message

Revision ID: a71d9387b497
Revises: 622de77c9065
Create Date: 2024-08-16 07:25:25.421883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71d9387b497'
down_revision = '622de77c9065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritos')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mass', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('hair_color', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('skin_color', sa.String(), nullable=False))
        batch_op.drop_constraint('people_email_key', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('people_email_key', ['email'])
        batch_op.drop_column('skin_color')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('mass')

    op.create_table('favoritos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='favoritos_pkey'),
    sa.UniqueConstraint('email', name='favoritos_email_key'),
    sa.UniqueConstraint('name', name='favoritos_name_key')
    )
    # ### end Alembic commands ###
